### ISSUE TITLE
module-ladspa-sink creates unmovable connection errors without source

### ISSUE THREAD

**Issue by einalex** [futpib/pagraphcontrol#1]
see [screenshot](https://cloud.aegir.space/index.php/s/eM8rGyWELb4qnBp)

To reproduce first create a new null sink and then add a module:
1)
module name: module-null-sink
parameters: sink_name=Mic sink_properties=device.description="Mic" channels=1
2)
module name: module-ladspa-sink
parameters: channels=1 sink_name=compressor sink_master=Mic plugin=sc4m_1916 label=sc4m control=1,1.5,401,-15,2,5,1 sink_properties=device.description="compressor"

**Comment by futpib** [comment]
Thanks for reporting, you should be able to get the fixed version from AUR.
