### ISSUE TITLE
How do I route something to two places at once?

### ISSUE THREAD

**Issue by MaryWeeb** [futpib/pagraphcontrol#19]
There are no guides on how to do this, dragging does not work, I am only able to move currently existing routes. Additionally, I am unable to route to input devices or other applications.

**Comment by futpib** [comment]
Firstly, you should know that this is only a front-end to PulseAudio, so  pagraphcontrol can do only what PulseAudio can.

This is not a pagraphcontrol issue, although it could do something smart about this and hide the underlying PulseAudio machinery, I'm not interested in implementing this.

A more appropriate place to ask this is StackOverflow or any PulseAudio or Linux support forum. I'll answer anyway.

### I am unable to route to input devices or other applications

How do you imagine an *input* device (like a microphone) could play any sound? This should not be possible and it is not.

In PulseAudio you can not pipe audio completely arbitrarily. Instead, a client (an application like a music player or audio recording software) creates a "source output" (for recording) or "sink input" (for playback) and reads or writes sound from a source or into a sink. A client may allow these streems to be moved between different sources or sinks (almost all clients do allow this). pagraphcontrol basically provides a UI for you to move them around.

### How do I route something to two places at once

#### Use [`module-combine-sink`](https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/Modules/#module-combine-sink)

1. Find the sinks you want to combine (2 or more):
```
pacmd list-sinks | grep -E 'name:|device\.description ='
```
Output may look like this:
```
name: <alsa_output.pci-0000_00_1f.3.analog-stereo>
        device.description = "Built-in Audio Analog Stereo"
name: <tunnel-sink.tcp_futpib-desktop.lan>
        device.description = "E-Mu 0202 Digital Stereo (IEC958) on futpib@futpib-desktop"
name: <tunnel-sink.tcp_futpib-desktop.lan.2>
        device.description = "GM206 High Definition Audio Controller Digital Stereo (HDMI 3) on futpib@futpib-desktop"
```
2. Combine them with [`combine-sink`](https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/Modules/#module-combine-sink) creating a virtual "Simultaneous output" sink
```
pacmd load-module module-combine-sink slaves=alsa_output.pci-0000_00_1f.3.analog-stereo,tunnel-sink.tcp_futpib-desktop.lan.2
```
3. Direct you application output to the "Simultaneous output" sink you created
![image](https://user-images.githubusercontent.com/4330357/75584634-341fc600-5a81-11ea-9676-de5e57c82d58.png)
You should now hear your sound on the sinks you combined

#### Use a bunch of [`loopbacks`](https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/Modules/#module-loopback) optionally with a [`null-sink`](https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/Modules/#module-null-sink).

1. (Optional) Create a null sink
* From context menu:
![image](https://user-images.githubusercontent.com/4330357/75585074-582fd700-5a82-11ea-89e3-1644b542c228.png)
* Or from command line:
```
pacmd load-module module-null-sink
```

2. Create a loopback
* From context menu:
![image](https://user-images.githubusercontent.com/4330357/75584912-eeafc880-5a81-11ea-985f-890e4ace786f.png)
* Or from command line:
```
pacmd load-module module-loopback
```

3. Direct the audio from a "Monitor sink" of the null output to each of the sinks through loopbacks
![image](https://user-images.githubusercontent.com/4330357/75585320-d8eed300-5a82-11ea-87b6-a81643d81d7b.png)

**Comment by maxenced** [comment]
Just fwiw, I'm currently using the 2nd option with loopbacks. The main drawback of the first one is that you need to unload the whole combine module if you want to change routing. In my case (multiroom setup), I need to be able to reroute audio on the fly, so loopbacks are much better : 
* Just create one null input for each audio input you need. I also updated alsa config so they appear in alsa cards
* in my case, add an extra bunch of module-remap-sink, as I need to be able to send on specific output of an 8 outputs card (each one going to dedicated speaker)
* Create loopbacks for each mapping you want

With this setup you can just:
* unload a loopback module to drop sound to a speaker, with no sound drop on other speakers
* load a new loopback module to add sound to a speaker, still with no sound drop on other speakers
