### ISSUE TITLE
Blank screen on ubuntu eoan

### ISSUE THREAD

**Issue by rogerjames99** [futpib/pagraphcontrol#24]
Apologies for using issues to raise a question.

I am trying to get this working on ubuntu eoan. Using the latest node.js etc. Build is ok. But just get a blank unresponsive screen. I can see from the source that there is logging. How do I turn it on. Where does the log go. Is there a forum or mailing list where this program is discussed?

Thanks,

Roger

**Comment by timbuntu** [comment]
I seem to have a similiar problem on Arch Linux.
I installed the aur package, and am using wayland with sway and nouveau drivers.
When I start pagraphcontrol, I only get a blank, gray window. 
If I start it from terminal, it produces the following output:
```
~ » pagraphcontrol
MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to open nouveau (search paths /usr/lib/dri)
failed to load driver: nouveau
MESA-LOADER: failed to open kms_swrast (search paths /usr/lib/dri)
failed to load driver: kms_swrast
MESA-LOADER: failed to open swrast (search paths /usr/lib/dri)
failed to load swrast driver
```
Although the drivers seem to be there:
```
~ » ls /usr/lib/dri
i915_dri.so  iris_dri.so        nouveau_dri.so        nouveau_vieux_dri.so  r200_dri.so  r600_dri.so        radeon_dri.so    radeonsi_drv_video.so  swrast_dri.so       virtio_gpu_dri.so
i965_dri.so  kms_swrast_dri.so  nouveau_drv_video.so  nvidia_drv_video.so   r300_dri.so  r600_drv_video.so  radeonsi_dri.so  s3g_drv_video.so       vdpau_drv_video.so  vmwgfx_dri.so
```

**Comment by timbuntu** [comment]
I now found a possible "fix". It seems that the problem was that my gpu is blacklisted for hardware acceleration/webGL by the chromium renderer used by electron.

The way I got it work is by calling pagraphcontrol with `--ignore-gpu-blacklist --enable-gpu-raterization --enable-zero-copy`

**Comment by rogerjames99** [comment]
That fixed it me as well thanks. Still no log output when run in terminal though.
