### ISSUE TITLE
Missing icons on Arch linux

### ISSUE THREAD

**Issue by Duologic** [futpib/pagraphcontrol#26]
Crosspost: https://aur.archlinux.org/packages/pagraphcontrol-git/#comment-742422

I'm on Arch and unable to get the icons to show up, it only shows application icons but not device icons. Adwaita and Hicolor icon themes installed, I have tested with and without gtk-3.0 settings.ini, no dice.

I added some extra logging and tried to find the cause with the inspector, it seems it doesn't find the icon theme directory. 

Any hints would be helpful.

**Comment by ktosiek** [comment]
I had similar problem on Ubuntu, I think there are a few problems here:
1. pagraphcontrol only looks for ~/.config/gtk-3.0/settings.ini, and not all the places where GTK+ looks. I'm trying to fix this in #31.
2. Icon names used are missing in some themes (notably Ubuntu's Yaru). Adding "gnome" as fallback works for me, but I'm not sure what The Right Way is. This also goes for icon names received from PA, so I think some kind of fallback will be necessary.

**Comment by Duologic** [comment]
Tested this, didn't fix the icons, don't have time to dive deeper into it right now.

**Comment by ashb** [comment]
I found the problem for this, at least for me

The `/usr/share/icons/Adwaita/index.theme` file has a trailing comma in the `Directories=` stanza. Removing that makes the icons appear.

I'll open a PR to fix this in freedesktop-icons, lets hope it gets merged and released.

**Comment by ashb** [comment]
https://github.com/bastimeyer/freedesktop-icons/pull/8

**Comment by ashb** [comment]
I'm still missing _some_ icons though, and some are not what I expected:

![image](https://user-images.githubusercontent.com/34150/101358139-56f1cd00-3892-11eb-8667-adb7014ce58d.png)


AKG N60NC are my headphones, and Blue Snowball is my mic.

**Comment by ashb** [comment]
Oh - my headphones are connected over bluetooth:

```
		device.icon_name = "audio-headset-bluetooth"
```

but I have no icon for that.
```
$ find /usr/share/icons -name 'audio-headset-bluetooth*'
$
```

**Comment by Duologic** [comment]
Looks like the PR got merged, awesome work.

**Comment by futpib** [comment]
Thanks, updated `freedesktop-icons` dependency is now in master and on aur.

**Comment by Duologic** [comment]
I can confirm it works! Thanks for the tool and the work put into finding this bug.
