### ISSUE TITLE
Rendering error because flag is deprecated

### ISSUE THREAD

**Issue by CCF100** [futpib/pagraphcontrol#27]
`$ pagraphcontrol
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397`

`(electron) 'setAutoHideMenuBar function' is deprecated and will be removed. Please use 'autoHideMenuBar property' instead.`
![image](https://user-images.githubusercontent.com/29297989/84851079-030ed580-b01f-11ea-9012-3c1a4d2207d6.png)

**Comment by futpib** [comment]
Warnings were not the reason for broken colors, but they should be addressed someday too.
