### ISSUE TITLE
incompatible module when trying to use yarn install on linux mint 19.3

### ISSUE THREAD

**Issue by Superbug50** [futpib/pagraphcontrol#28]
When i was useing the "yarn install"  and "yarn build" command it showed me this:

> `root@JLM:/pagraphcontrol# **yarn install**
> yarn install v1.22.4
> [1/5] Resolving packages...
> [2/5] Fetching packages...
> error ava@3.9.0: The engine "node" is incompatible with this module. Expected version ">=10.18.0 <11 || >=12.14.0 <12.17.0 || >=12.17.0 <13 || >=14.0.0". Got "13.11.0"
> error Found incompatible module.
> info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
> root@JLM:/pagraphcontrol# **yarn build**
> yarn run v1.22.4
> $ electron-packager --overwrite . pagraphcontrol --out dist --asar
> /bin/sh: 1: electron-packager: not found
> error Command failed with exit code 127.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> root@JLM:/pagraphcontrol# 
 
**_Should i change my yarn version?_**

**Comment by futpib** [comment]
You should probably change your `node` version. Use your system's package manager or `nvm`.

This line tells exactly what's the problem:

```
error ava@3.9.0: The engine "node" is incompatible with this module. Expected version ">=10.18.0 <11 || >=12.14.0 <12.17.0 || >=12.17.0 <13 || >=14.0.0". Got "13.11.0"
```

You can also try running `yarn install --production` (instead of `yarn install`). This should not pull `ava@3.9.0` which is incompatible with your `node` version.
