### ISSUE TITLE
Package not building with --asar option

### ISSUE THREAD

**Issue by CodedBinary** [futpib/pagraphcontrol#40]
Arch linux, linux-hardened kernel, have `pacman -Syu`'d. When installing this, the build doesn't seem to generate a package. As a result, the installation (with yay) fails with the following error:

```
==> Starting package()...
/home/$USER/.cache/yay/pagraphcontrol-git/PKGBUILD: line 33: cd: pagraphcontrol/dist/*: No such file or directory
==> ERROR: A failure occurred in package().
```

Manually building with the ubuntu instructions of course doesn't fix this. I managed to build it by omitting the --asar option. That is, when using `yay -S pagraphcontrol-git --editmenu`, I edited the PKGBUILD by replacing `yarn build` with `electron-packager --overwrite . pagraphcontrol --out dist`. From a quick read of the documentation of electron-packager, it seems like there might be a difference in our default options for the --asar option, but I'm not a developer and I don't know much about this.

**Comment by futpib** [comment]
I removed the `--asar` option from package.json an got it to upgrade (I had this bug reproducible on one machine with `yay`, but not consistently with `makepkg` which was wierd). May work now, but I never got to the bottom of this issue.
