### ISSUE TITLE
No multiple sink inputs for all apps ?

### ISSUE THREAD

**Issue by ogmkp** [futpib/pagraphcontrol#60]
Hello and thank you for this project!

I use it for various applications, but for OBS Studio, it only displays one sink-input while Chromium displays several.

![Capture du 2021-08-19 10-03-08](https://user-images.githubusercontent.com/17526713/130032960-ae0dea64-437a-4298-b8da-6d2f02cd8f85.png)

While I have them on CLI:
$ pactl list sink-inputs short 
4	2	-	module-ladspa-sink.c	float32le 2ch 44100Hz
13	3	25	protocol-native.c	float32le 2ch 44100Hz   < Chromium
15	2	28	protocol-native.c	s16le 2ch 44100Hz   < OBS
16	2	28	protocol-native.c	s16le 2ch 44100Hz   < OBS
17	2	28	protocol-native.c	s16le 2ch 44100Hz   < OBS
18	3	35	protocol-native.c	float32le 2ch 44100Hz   < Chromium

Thanks !

**Comment by maxdrfr** [comment]
Finally, I have the same problem with games (running proton from steam).
Is there a way to separate and route these streams?

**Comment by ogmkp** [comment]
Since the arrival of pipewire, routing problems have been solved, thank you.
