### ISSUE TITLE
It is hard to differentiate between several audio feeds from the same source

### ISSUE THREAD

**Issue by Managor** [futpib/pagraphcontrol#7]
As an example: If you have several youtube videos open at the same time, there are several arrows without a clear distiction which one is which.
![See image](https://user-images.githubusercontent.com/42655600/52183881-02ecac00-2815-11e9-946e-66c07f8d26fa.png)

I would propose a second bar under volume which moves along the the currently emitted sound. This would allow you to distinguish which arrow your current youtube video corresponds to.

**Comment by Managor** [comment]
Alright, that works. Is there no API for this in pulseaudio? `pavucontrol` has a working audiometer natively so I thought there would be something that you could hook up to. See here.
![peek 2019-02-04 11-45](https://user-images.githubusercontent.com/42655600/52200806-60fbac80-2872-11e9-862c-e6ab1c9ec691.gif)

**Comment by Managor** [comment]
Understood.

**Comment by schuellerf** [comment]
I think a similar functionality is already implemented when papeaks is installed (see readme.md)
